package org.ahlab;

import com.google.cloud.texttospeech.v1.AudioConfig;
import com.google.cloud.texttospeech.v1.AudioEncoding;
import com.google.cloud.texttospeech.v1.SynthesisInput;
import com.google.cloud.texttospeech.v1.SynthesizeSpeechResponse;
import com.google.cloud.texttospeech.v1.TextToSpeechClient;
import com.google.cloud.texttospeech.v1.VoiceSelectionParams;
import com.google.protobuf.ByteString;
import java.io.FileOutputStream;
import java.io.OutputStream;

public class Main {

  public static void main(String[] args) {
    String[] inputs = {
        /*" MagHair is a new haptic stimulation technique that stimulates the body hair without touching the skin.\n"
        ,
        " This is achieved by adapting magnetic locomotion techniques, To control strong magnetic fields on a wearable form factor\n"
        ,
        " and using magnetic cosmetics to augment the body hair and make it responsive to magnetic fields.\n"
        ,
        " The movements of the permanent magnet stimulate the body hair skin, generating a subtle and gentle touch sensation.\n"
        ,
        " The recipes are generated by mixing safe products,commonly used in commercial cosmetics.\n"
        ,
        " After applying it to hair samples, a setup measure the deflection of each of the hair based on a specific magnetic field"*/
        "We demonstrate how to modify an off-the-shelf webcam purchasable for less than 100 U.S.D. and mounting it to a 3d-printed specs frame."
    };
    int counter = 0;
    for (String input : inputs) {
      try {
        synthesizeText(input, ++counter);
      } catch (Exception e) {
        e.printStackTrace();
      }
    }

  }

  /**
   * Demonstrates using the Text to Speech client to synthesize text or ssml.
   *
   * @param text the raw text to be synthesized. (e.g., "Hello there!")
   * @throws Exception on TextToSpeechClient Errors.
   */
  public static void synthesizeText(String text, int i) throws Exception {
    String name = ""
        + "kaluwa_v3_" + i + ".mp3";
    // Instantiates a client
    try (TextToSpeechClient textToSpeechClient = TextToSpeechClient.create()) {
      // Set the text input to be synthesized
      SynthesisInput input = SynthesisInput.newBuilder().setText(text).build();

      // Build the voice request
      VoiceSelectionParams voice =
          VoiceSelectionParams.newBuilder()
              .setLanguageCode("en-US") // languageCode = "en_us"
//              .setLanguageCode("en-GB")
//              .setName("en-GB-Wavenet-A")

//              .setName("en-US-Wavenet-A")
              .setName("en-US-Wavenet-F")
              .build();

      // Select the type of audio file you want returned
      AudioConfig audioConfig =
          AudioConfig.newBuilder()
              .setAudioEncoding(AudioEncoding.MP3) // MP3 audio.
              .setSpeakingRate(1)
              .setPitch(1)
              .build();

      long start = System.currentTimeMillis();
      // Perform the text-to-speech request
      SynthesizeSpeechResponse response =
          textToSpeechClient.synthesizeSpeech(input, voice, audioConfig);
      long estimate = System.currentTimeMillis() - start;
      // Get the audio contents from the response
      ByteString audioContents = response.getAudioContent();

      // Write the response to the output file.
      try (OutputStream out = new FileOutputStream(name)) {
        out.write(audioContents.toByteArray());
        System.out.println("Audio content written to file: " + name + ", time: " + estimate);
      }
    }
  }
}
